### PR TITLE
Api client

### LINKED ISSUE #3: API calls
## Connecting to ARgorithmServer

The `APIClient` class has to be created whose functions will be called by button manager
functions that will be required: 
- `connect` : to connect to server and check if auth is required
- `create` : to create user account
- `authenticate` : to authenticate user credentials and store JWT token
- `list` : gets list of argorithms from connected server
- `run` : gets states from server after execution

### PR DESCRIPTION
**Pull request by alanpjohn**
closes #3 

## ARgorithmAPI

[forthebadge](https://forthebadge.com)

ARgorithmAPI has been created with the following functions:

- `connect` : connects to end point
- `login` : log in to user account
- `create` : create user account
- `verify` : checks for pre-existing login credentials
- `list` : gets list of argorithm from server

### Usage

get the imports

```cs
using ARgorithmAPI;
using ARgorithmAPI.Models;
```

#### `connect`

```cs
    public void connect(){
        StartCoroutine(
            APIClient.Instance.connect(
                "https://argorithm.el.r.appspot.com",
                (r) => callback(r)
            )
        );
    }

    void callback(ConnectionResponse c){
        Debug.Log(c.status);    
    }
```

The ConnectionResponse.status can have following values

- FAILURE: Error has occured
- AUTH: Connection has been estabilished and Authentication is required
- SUCCESS: Connection has been estabilished and Authentication is not required

#### `create`

```cs
    public void createAccount(){
        StartCoroutine(
            APIClient.Instance.create(
                new Account {
                    email="sample@email.com",
                    password="NotARealPassword"
                },
                (r) => callback(r)
            )
        );
    }

    void callback(CreationResponse c){
        Debug.Log(c.status);
    }
```

The CreationResponse.status can have following values

- FAILURE: Error has occured
- SUCCESS: User account has been created
- EXISTING: Email is already registered
- NOT_ALLOWED: Authentication feature at endpoint is disabled, skip login

#### `login`

```cs
    public void login(){
        StartCoroutine(
            APIClient.Instance.login(
                new Account {
                    email="sample@email.com",
                    password="NotARealPassword"
                },
                (r) => callback(r)
            )
        );
    }

    void callback(LoginResponse c){
        Debug.Log(c.status);
    }
```

The LoginResponse.status can have following values

- FAILURE: Error has occured
- SUCCESS: Login successful
- NOT_ALLOWED: Authentication feature at endpoint is disabled, skip login
- NOT_FOUND: Email is not registered
- INCORRECT_PASSWORD: Password is incorrect

#### `verify`

```cs
    void verify(){
        StartCoroutine(
            APIClient.Instance.verify(
                (r) => callback(r)
            )
        );
    }
    
    void callback(LoginResponse c){
        Debug.Log(c.status);
    }
```

The LoginResponse.status can have following values

- FAILURE: Error has occured
- SUCCESS: Login successful
- RESET: Will have to login again

#### `list`

```cs
    void list(){
        StartCoroutine(
            APIClient.Instance.list(
                (r) => callback(r)
            )
        );
    }

    void callback(ARgorithmCollection lar){
        foreach (ARgorithm item in lar.items)
        {
            Debug.Log(item.argorithmID);
        }
    }
```

> Check out the models in `ARgorithmAPI/Models/Models.cs`

### The `run` problem

So I was implementing run and it is tad more complicated due to parameters and my amatuer C# skills and also with [that issue](https://github.com/ARgorithm/toolkit/issues/3) still at large. But the other functions work and @Vin-dictive  can start his work on #4 . We can brainstorm and add the `run` later

## Added Readme

Simple README.md added

### CODE REVIEW

**Comment by alanpjohn** [comment]
also dont worry, I removed Codacy after i saw it was linked to this repo as well
Should not affect future pull requests or commits, and it is now stuck at `in progress` because of that

FYI: The grade was `A`

**Review by Vin-dictive — APPROVED** [review]

**Comment by alanpjohn** [comment]
Closes #4

@Vin-dictive is making his UI updates in this pull request as well so we'll review and merge that here as well

**Review by yatharthmathur — APPROVED** [review]

**Comment by alanpjohn** [comment]
Going to refactor and change the JSON parser we use from the inbuilt JSON utility to [JSON.net](https://assetstore.unity.com/packages/tools/input-management/json-net-for-unity-11347#description) as it is much more friendly to dynamic objects and can parse JSON objects using key-value.

**Comment by yatharthmathur** [comment]
You'll have to make sure the build for Android is supported with it

**Comment by alanpjohn** [comment]
> Officially Supported Platforms: We officially support all Unity platforms ..

what they say, i have added the link in the previous message, you can double check if you want

**Comment by alanpjohn** [comment]
Migrated to JSON.net

## Added `run` functionality

The following models have been added to support run

- `ExecutionRequest`
- `ExecutionResponse`
- `State`

If you see the design of `State`, you'll notice that `state_def` is of type [`JObject`](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_Linq_JObject.htm). You can use the `GetValue(string key)` command to extract values out it like you would do in a dictionary. It is at the time of this commit, the best way to handle the dynamic structure of stateset. `JObject` has also been utilised in `ARgorithm` model.

The `APIClient`.`run` method uses a ExecutionRequest in which you have to define `argorithmID` and `parameters`. You can pass a empty JObject instance to run the default parameters. Once the form for taking user input is ready, we can pass a `JObject` that has the input defined and pass that into `run`

```cs
StartCoroutine(
    APIClient.Instance.run(
        new ExecutionRequest{
            argorithmID="bubblesort",
            parameters=new JObject()
        },
        (r) => callback(r)
    )
);
```
> Will add code comments for documentations later, forgot about that

**Pull request merged**
