### PR TITLE
UI updates

### PR DESCRIPTION
**Pull request by yatharthmathur**
Updates and fixes to UI
- [x] **Parameters menu** : UI element to select parameters to the the ARgorithm
- [x] **Scrolling** : Added scrolling feature to the menu where it was required using ScrollRect component
- [x] **Splash Screen** : Added a splash screen on App startup
- [x] **Icons** : Added app icons (adaptive) for android application
- [x] **Landscape mode for ARStage** : landscape mode feature added to the ARStage scene
- [x] **Comments** : Fixing comment behaviour
- [x] **Scene-Management** : Added scene management and loading between two scenes
- [x] **State counter** : keeping a counter for each step in the state list
- [x] **Removing top panel in ARStage UI** : UI Clean up

### CODE REVIEW

**Comment by alanpjohn** [comment]
@yatharthmathur Add some description about the changes as well

**Comment by Vin-dictive** [comment]
@TheForeverLost can you give me the Icons you have made according to adaptive icons setup. Also  @yatharthmathur, @TheForeverLost pointed out an issue where the back to previous state button does not work as expected. I checked it out in bubblesort where the  back to previous state button was getting stuck at state 11/32. We need to check this out.

**Comment by yatharthmathur** [comment]
> @yatharthmathur Add some description about the changes as well

Done

**Comment by alanpjohn** [comment]
Uhmm what about search bar??
Which we would need as ARgorithms increase? I thought we were gonna have that in this pull request?@yatharthmathur

**Comment by yatharthmathur** [comment]
Oop

**Pull request merged**
